 set nocompatible               " be iMproved

 syntax on

 "-----------------
 " Bundle Manager
 "-----------------
 " Brief help (or see https://github.com/gmarik/vundle)
 " :BundleList          - list configured bundles
 " :BundleInstall(!)    - install(update) bundles
 " :BundleSearch(!) foo - search(or refresh cache first) for foo
 " :BundleClean(!)      - confirm(or auto-approve) removal of unused bundles
 "
 " see :h vundle for more details or wiki for FAQ
 " NOTE: comments after Bundle command are not allowed..
 
 filetype off                   " required! (By Vundle)

 set rtp+=~/.vim/bundle/vundle/
 call vundle#rc()

 " let Vundle manage Vundle
 " required! 
 Bundle 'gmarik/vundle'

 " My Bundles:
 " Bundle 'tpope/vim-fugitive' -> original repos on github
 " Bundle 'FuzzyFinder'        -> vim-scripts repos
 " Bundle 'git://git.wincent.com/command-t.git' -> non github repos
 
  Bundle 'kien/ctrlp.vim'
  Bundle 'tpope/vim-rails'
  Bundle 'tpope/vim-abolish'
  Bundle 'tpope/vim-bundler'
  Bundle 'tpope/vim-surround'

  Bundle 'scrooloose/nerdtree.git'
  "Auto open if no file specified when opening VIM
  autocmd vimenter * if !argc() | NERDTree | endif 
  "Auto close VIM if only NERDTree is open
  autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
  map <F2> :NERDTreeToggle<CR>

 filetype plugin indent on     " required! (By Vundle)

